post intellj_kde_lag_spike_workaround "Fixing Intellj IDEA lag spikes on OpenSUSE KDE Plasma 6" 2025-04-17 "software"
post dcss_gods_surface "DCSS deities on the surface" 2025-03-20 "dcss games dnd"
post opensuse_mic "Fixing HP Victus 15 internal microphone drivers by compiling patched auto-updating kernel with openSUSE Tumbleweed Open Build Service" 2024-12-25 "debugging software"
post dcss_dscj "DCSS win: Powerfully lucky DsCj" 2024-09-29 "dcss games"
post opensuse "Switching to openSUSE Tumbleweed" 2024-08-06 "software"
post cdda_arcana_technoclysm_2 "Arcana Technoclysm update: Magical UPS, whistle crafting, and bionic installation" 2024-05-17 "software games cdda"
post minecraft_amethyst_farm "First Version of an Amethyst Farm" 2024-01-14 "games minecraft"
post cdda_improvements "Recent great improvements in Cataclysm: DDA" 2023-11-02 "games cdda"
post cdda_arcana_technoclysm "Arcana Technoclysm: A small mod for Cataclysm: DDA" 2023-10-20 "software games cdda"
POST_BLURB="Sci-fi, history, Mark Twain!" POST_INTERNAL="reading_list#2023-10-06" post reading_list_3 "Reading list update #3" 2023-10-06 "reading discovery"
post tpt_world_map "World map for a Wesnoth campaign: The Paradise Trap" 2023-09-28 "software games wesnoth"
post dcss_sh "The new DCSS shapeshifter background (first win)" 2023-07-28 "games dcss"
POST_EXTERNAL="https://github.com/CleverRaven/Cataclysm-DDA/pull/66639" post make_horses_milkable "Make horses milkable" 2023-07-03 "cdda software"
POST_BLURB="Culture and mystery!" POST_INTERNAL="reading_list#2023-06-06" post reading_list_2 "Reading list update #2" 2023-06-06 "reading discovery"
POST_UPDATED="2025-01-05" post dillo_test "The Dillo Test" 2023-05-11 "dev software website"
POST_BLURB="Abercrombie's grim darkness, Atwood's dystopia, Brooks' apocalypse, and more!" POST_INTERNAL="reading_list#2023-05-08" post reading_list_1 "Reading list update #1" 2023-05-08 "reading discovery"
post mapper0_6_2 "Mapping tool 0.6.2 release & thanks to all testers" 2023-05-08 "mappingtool release software"
post graduation "I graduated from MVNU!" 2023-05-07 "academics life"
POST_EXTERNAL="https://www.mvnu.edu/news/mvnu-students-shine-during-symposium-for-undergraduate-research-and-creative-works" post mvnu_surc_announcement "MVNU sURC press release featuring my mapping tool" 2023-04-25 "academics mappingtool"
post roadtrip_intro "Prototype post-apocalyptic roadtrip simulator for the Minetest engine" 2023-04-23 "roadtrip minetest games software"
POST_UPDATED="2023-04-25" post mvnu_surc "First place prize for my mapping tool presentation at MVNU's sURC" 2023-04-21 "academics mappingtool software"
post textengine_intro "Toward the ultimate text adventure game engine" 2023-04-21 "software games textengine discovery"
POST_EXTERNAL="https://github.com/mapper1024/mapper1024/wiki/Quick-Start" post mapper_quick_start "Mapping tool quick start guide" 2023-04-20 "mappingtool software"
post cdda_ernie_road_trip "CDDA big world showcase: Ernie's great road trip" 2023-04-11 "games cdda"
POST_UPDATED="2023-04-07" post mapper_gifs "OBS Studio -> ffmpeg -> ImageMagick for an optimized gif" 2023-04-06 "discovery utilities software"
post lusha_answers_version_2 "Scene draft: Lusha tries to get answers, version 2" 2023-03-29 "writing scene"
post opca_win "30th DCSS win: Octopode Cinder Acolyte of Jiyva" 2023-03-28 "games dcss"
post cs_mft "I took the ETS major field test for computer science" 2023-03-16 "deepdive software academics"
post debugging_network "Debugging slow boot and a clogged router" 2023-03-08 "debugging software"
post mapper0_6 "Mapping tool 0.6 release" 2023-02-16 "mappingtool release software"
POST_UPDATED="2023-03-29" post lusha_answers_version_1 "Scene draft: Lusha tries to get answers, version 1" 2023-02-15 "writing scene"
POST_SERIES=cdda_erik post cdda_erik_5 "Erik Otto #5: Gaining allies" 2023-02-14 "games letsplay cdda cdda_erik"
POST_SERIES=cdda_erik post cdda_erik_4 "Erik Otto #4: Arsenal" 2023-02-08 "games letsplay cdda cdda_erik"
post cdda_no_hole "Autodrive into a crater fix" 2023-02-08 "cdda debugging software"
POST_SERIES=cdda_erik post cdda_erik_3 "Erik Otto #3: Preparing for battle" 2023-02-06 "games letsplay cdda cdda_erik"
POST_SERIES=cdda_erik post cdda_erik_2 "Erik Otto #2: Base building and car collecting" 2023-02-06 "games letsplay cdda cdda_erik"
POST_SERIES=cdda_erik post cdda_erik_1 "Erik Otto #1: Used car cult salesman" 2023-02-05 "games letsplay cdda cdda_erik"
POST_SERIES=cdda_raymon post cdda_raymon_postmortem "CDDA let's play: Post-mortem" 2023-02-02 "games letsplay cdda cdda_raymon"
POST_SERIES=cdda_raymon post cdda_raymon_4 "Raymon Ortega #4: The End" 2023-02-02 "games letsplay cdda cdda_raymon"
POST_SERIES=cdda_raymon post cdda_raymon_3 "Raymon Ortega #3: Camping out of town" 2023-02-01 "games letsplay cdda cdda_raymon"
POST_SERIES=cdda_raymon post cdda_raymon_2 "Raymon Ortega #2: Battery Heist and a Sweet Chariot" 2023-01-31 "games letsplay cdda cdda_raymon"
POST_SERIES=cdda_raymon post cdda_raymon_1 "Raymon Ortega #1: Would-be Wizard" 2023-01-29 "games letsplay cdda cdda_raymon"
post more_rss_feeds "More RSS feeds!" 2023-01-27 "software website"
post test_post "Test post, please ignore" 2023-01-27 ""
post discovering_random_websites "Discovering random websites" 2023-01-26 "discovery"
post finding_discussion_diff_blog "Finding discussion about diff.blog" 2023-01-25 "discovery deepdive"
post naga_hexslinger_win "29th DCSS win: Naga Hexslinger" 2023-01-25 "games dcss"
post diff_blog "I'm on diff.blog" 2023-01-25 "software website"
post made_rss_feed "I made an RSS feed!" 2023-01-22 "software website"
post mapper0_5 "Mapping tool 0.5 release" 2023-01-21 "mappingtool release software"
post website_build_script "benleskey.com build script" 2023-01-12 "software website"
post mapper0_4 "Mapping tool 0.4 release" 2023-01-04 "mappingtool release software"
post mapper0_3 "Mapping tool 0.3 release" 2022-10-26 "mappingtool release software"
post mapper0_1 "Mapping tool 0.1 release" 2022-08-01 "mappingtool release software"
